# Generated by Django 6.0.4 on 2026-05-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesult',
            name='interview_prep',
            field=models.JSONField(default=dict),
        ),
    ]
