# Generated by Django 6.0.5 on 2026-05-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0002_airesult_interview_prep'),
    ]

    operations = [
        migrations.AddField(
            model_name='airesult',
            name='ats_issues',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='airesult',
            name='ats_keywords_found',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='airesult',
            name='ats_keywords_missing',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='airesult',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
    ]
